-- DATA DEFINITION LANGUAGE
-- Tạo cấu trúc bảng

USE QLHT
GO


-- Tạo Bảng CTHB(CHI TIẾT HỌC BỔNG)
CREATE TABLE CTHB
(
	MAHB			VARCHAR(20)			PRIMARY KEY,
	TRIGIA			FLOAT				NOT NULL		DEFAULT 0,			
	TGDK			DATE				NOT NULL,
	GHICHU			NVARCHAR(1000)		NULL,
	SLDK			INT					NOT NULL		DEFAULT 0,
	TENHB			NVARCHAR(1000)		NOT NULL		DEFAULT 'Chưa được đặt tên',
)
GO

-- Tạo bảng DSHB(DANH SÁCH HỌC BỔNG)	
CREATE TABLE DSHB
(
	SL				INT					NOT NULL		DEFAULT 0,
	TONGTIEN		FLOAT				NOT NULL		DEFAULT 0,
	DVTC			NVARCHAR(1000)		NULL			DEFAULT 'Chưa Xác Định',
	MAHB			VARCHAR(20),

	-- Khóa ngoại MAHB tham chiếu đến khóa chính MAHB trong bảng CTHB
	FOREIGN KEY		(MAHB)			REFERENCES CTHB(MAHB)
)
GO
