-- DATA DEFINITION LANGUAGE
-- Tạo cấu trúc bảng

USE QLHT
GO


-- Tạo Bảng MONHOC
CREATE TABLE MONHOC
(
	MAMH			VARCHAR(20)			PRIMARY KEY,
	TENMH			NVARCHAR(100)			NOT NULL,
	TINCHI			INT				NOT NULL,
	QT			FLOAT				NULL,
	GK			FLOAT				NOT NULL,		
	TH			FLOAT				NULL,
	CK			FLOAT				NOT NULL, 
	DTBMON			FLOAT				NOT NULL
)
GO 

-- Tạo bảng KQHT(KẾT QUẢ HỌC TẬP)
CREATE TABLE KQHT
(
	MSSV			VARCHAR(20)			PRIMARY KEY,
	NAMHOC			INT				NOT NULL		DEFAULT 2015,
	HOCKY			INT				NOT NULL		DEFAULT 1,
	DTBHOCKY		FLOAT				NOT NULL		DEFAULT 0,
	MAMH			VARCHAR(20)

	-- Khóa ngoại MAMH tham chiếu đến khóa chính MAMH trong bảng MONHOC
	FOREIGN KEY		(MAMH)			REFERENCES MONHOC(MAMH)
)
GO
